### ISSUE TITLE
Error "example_{n}.nii.gz is not a gzip file"

### ISSUE THREAD

**Issue by Microdeep-ZL** [wtclarke/mrs_nifti_standard#13]
I tried `mrs_tools info example_03.nii.gz` but got the following error
```
$ mrs_tools info example_03.nii.gz 
Traceback (most recent call last):
  File "/home/nmr/.conda/envs/fslmrs/bin/mrs_tools", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/mrs_tools/__init__.py", line 159, in main
    args.func(args)
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/mrs_tools/__init__.py", line 171, in info
    data = NIFTI_MRS(file)
           ^^^^^^^^^^^^^^^
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/nifti_mrs/nifti_mrs.py", line 104, in __init__
    self.image = Image(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/fsl/data/image.py", line 1261, in __init__
    nibImage   = nib.load(image, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/nibabel/loadsave.py", line 115, in load
    raise ImageFileError(msg)
nibabel.filebasedimages.ImageFileError: File /home/nmr/Projects/FSLMRS_test/mrs_nifti_standard/example_data/examples/example_03.nii.gz is not a gzip file
```
Other example files all have the same error.

After that, I tried to load these files in nibabel in python, and got exactly the same error.

My nibabel version is 5.2.1 what could go wrong?

**Comment by wtclarke** [comment]
Hi, you need to install git LFS before cloning the repository. Without this the files will just be little stubs.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Septem ***@***.***>
Sent: Friday, October 18, 2024 2:57:37 AM
To: wtclarke/mrs_nifti_standard ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wtclarke/mrs_nifti_standard] Error "example_{n}.nii.gz is not a gzip file" (Issue #13)


I tried mrs_tools info example_03.nii.gz but got the following error

$ mrs_tools info example_03.nii.gz
Traceback (most recent call last):
  File "/home/nmr/.conda/envs/fslmrs/bin/mrs_tools", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/mrs_tools/__init__.py", line 159, in main
    args.func(args)
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/mrs_tools/__init__.py", line 171, in info
    data = NIFTI_MRS(file)
           ^^^^^^^^^^^^^^^
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/nifti_mrs/nifti_mrs.py", line 104, in __init__
    self.image = Image(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/fsl/data/image.py", line 1261, in __init__
    nibImage   = nib.load(image, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nmr/.conda/envs/fslmrs/lib/python3.12/site-packages/nibabel/loadsave.py", line 115, in load
    raise ImageFileError(msg)
nibabel.filebasedimages.ImageFileError: File /home/nmr/Projects/FSLMRS_test/mrs_nifti_standard/example_data/examples/example_03.nii.gz is not a gzip file


Other example files all have the same error.

After that, I tried to load these files in nibabel in python, and got exactly the same error.

My nibabel version is 5.2.1 what could go wrong?

**Comment by Microdeep-ZL** [comment]
Oh, thanks! I didn't notice the .nii.gz files were actually all text files. The problem has been resolved! I used the scripts in `data_genration` folder to generate those .nii.gz files.
